# configuration for https://ohi-science.nceas.ucsb.edu/gye_app
study_area:       1
git_owner:        OHI-Science
git_repo:         gye
git_slug:         OHI-Science/gye
git_url:          https://github.com/OHI-Science/gye
app_url:          https://ohi-science.nceas.ucsb.edu/gye_app
default_branch:   published
default_scenario: region2015
debug:            False
last_updated:     2015-03-20
ohicore_app:
  git_owner: jules32
  git_repo: gye
  git_branch: draft
  git_commit: initial commit

tabs_hide:        
- Calculate
- Report

