# configuration for https://ohi-science.nceas.ucsb.edu/gye
study_area:       Golfo de Guayaquil
git_owner:        OHI-Science
git_repo:         gye
git_slug:         OHI-Science/gye
git_url:          https://github.com/OHI-Science/gye
app_url:          http://ohi-science.nceas.ucsb.edu/gye
default_branch:   published
default_scenario: region2015
debug:            False
last_updated:     2015-05-07
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: 49aa4a3315fef420c3f9b73670d47324a762b7a2

tabs_hide:        
- Calculate
- Report

